project-trans/MtF-wiki

content/zh-cn/docs/medicine/check.md

激素六项检查内容初始填充

---

content/zh-cn/docs/srs/care.md

Signed-off-by: Septs <github@septs.pw>

fix: typo error

---

content/zh-cn/docs/srs/welfare.md

chore: add welfare

---

content/zh-cn/docs/hrt/jnuh1/index.md
content/zh-cn/docs/medicine/HRT.md

本地预览有些问题，`hugo server -D`提示渲染shortcode `csv-table`失败。我尽量参照既有模板编辑，但如有错漏，烦请指正。

Fix potential recipes committed by HRT doctress Gao

---

content/zh-cn/converter/main.js

fix: converter

---

content/zh-cn/docs/medicine/estrogen/oestrogel/index.md

duplicated

---

.github/workflows/build-gh-pages.yml

Revert "deploy to s3"

---

config/_default/menus.zh-hant.toml
content/zh-hant/_index.md
content/zh-hant/about.md
content/zh-hant/converter.md
content/zh-hant/cup-calculator.md

改進繁體中文版面用字

---

content/zh-cn/docs/vocal-training/software.md

信息来自于 Reddit Thread https://www.reddit.com/r/transvoice/comments/mvnxt9/vocal_pitch_monitor_for_pc/

添加推荐的Windows/Linux/macOS下的嗓音训练辅助软件

---

content/zh-cn/docs/friendship/index.md
layouts/shortcodes/shields/matrix.html

could you help me check how to write the matrix icon

try to add matrix

---

assets/customize.scss
layouts/shortcodes/mtf-wiki.html

fix: mtf.wiki identity

---

content/zh-cn/docs/_index.md

于此同时->与此同时
Signed-off-by: Leohearts <leohearts@leohearts.com>

minor fix: typo

---

content/en/docs/hrt/_index.md
content/en/docs/hrt/singapore/_index.md
content/en/docs/hrt/singapore/singapore-hrt-overview.md

add: english singapore hrt

---

content/zh-cn/docs/srs/id-card.md

fix: Guangxi is not a province

---

content/zh-cn/docs/srs/thailand/srs-overview-thailand.md

it's interesting that the zh-hant page is correct - -

fix: suporn clinic doesn't do colonvaginoplasty

---

content/zh-cn/docs/srs/id-card.md

Signed-off-by: Leohearts <leohearts@leohearts.com>

Fix: dead link in "SRS 性别重置手术=>证件变更指引"

---

content/zh-cn/docs/psyco/guangdong/zhao-suhua/index.md

Signed-off-by: 本宫略萌 <moejumi@qq.com>

更正链接；更正出诊时间

---

content/zh-hant/docs/medicine/estrogen/estradiol/index.md

更新失效照片連結及修正名稱（只寫伊黛歐不知道是藥品照片）。   
另外新增台灣食藥署連結提供伊黛歐仿單連結（PDF 檔）。
Signed-off-by: HybridGlucose <HybridGlucose@freedomwolf.cc>

更新正體中文伊黛歐內容

---

content/zh-cn/docs/srs/thailand/chettawut.md

Signed-off-by: Setsuna <kzsetsuna@outlook.jp>

Minor grammatical fixes

---

content/zh-cn/docs/hrt/canada/human-rights/index.md

添加了加拿大各省的几项人权状况

---

assets/customize.scss
content/en/_index.md
content/es/_index.md
content/ja/_index.md
content/zh-cn/_index.md
content/zh-cn/converter/_index.md
content/zh-cn/cup-calculator.md
content/zh-hant/_index.md
content/zh-hant/converter.md
content/zh-hant/cup-calculator.md
layouts/shortcodes/hide-mobile-navbar.html
layouts/shortcodes/shields/telegram.html
layouts/shortcodes/shields/twitter.html

Improve: 优化黑暗模式，微调页面

---

assets/customize.js

hidden-photo-toggle

---

content/en/_index.md
content/en/about.md
content/es/_index.md
content/es/about.md
content/ja/_index.md
content/ja/about.md
content/zh-cn/_index.md
content/zh-cn/about.md
content/zh-hant/_index.md
content/zh-hant/about.md
layouts/shortcodes/project-trans.html

* about.md: LOGO "MtF" padding -> padding:16px 16px 32px
* _index.md: LOGO "MtF" height -> 0.77em
* project-trans.html: height -> 0.75em

Fix padding and height of LOGO

---

content/zh-cn/docs/medicine/monitoring.md
content/zh-hant/docs/medicine/monitoring.md

由于北三的检查项目繁多，出于科普和补强 GAHT 所需监测项目之目的，大幅充实了酌情监测的项目：
- 肝功能增加有关比卡鲁胺的注意事项。
- 增加胰岛素、血脂（甘油三酯）、离子六项（钙，无机磷和铁）、甲状腺和甲状旁腺功能、血常规等事项。
- 为血糖和骨密度补充说明。
- 增补多份引用材料，并规范参考文献格式。

Enhanced info in Monitoring

---

content/zh-cn/docs/friendship.md

由 @Aleksanaa 创建，目前成员约 30 人，包括 @Cryolitia @CoelacanthusHex 。

Add friendship: NixOS 木桶饭

---

content/zh-cn/cup-calculator.md
content/zh-hant/cup-calculator.md

Revert cup-calculator related

---

content/zh-cn/docs/medicine/estrogen/gel/index.md

https://github.com/project-trans/2345.LGBT/pull/14

添加 雌二醇凝胶自制教程

---

content/zh-cn/docs/hrt/canada/UWaterloo/index.md

添加滑铁卢大学的HRT相关信息

---

content/zh-cn/docs/srs/us/heidi-wittenberg.md

- Update some information for consultation.
- Update procedure information.
- Update BMI requirement.
- Update insurance information.
- Add dilation requirements.
- Add letters' link.

docs(srs-us): Update Heidi Wittenberg's details.

---

content/zh-cn/docs/srs/china/xa-imc/index.md

docs(srs): add info for xa-imc

---

content/zh-cn/docs/medicine/estrogen/gel/index.md

本文介绍了一种基于wiki原先给出的教程、修改后配方和制备方法。本人所查到的文献及相关专利指出的乙醇的浓度与原配方给出的差距较大，故进行修改，同时该配方使用了原配方未使用的透皮剂。
本文的内容仍在完善，过几天有时间的话会补充参考的论文、资料，可以视作一种思路分享和探讨。

update: 一种可能更优的自制凝胶配方以及适合大量制作的方法

---

content/zh-cn/docs/srs/id-card.md

证件变更指引 | 成都学生集体户口可能无法变更姓名

---

content/zh-cn/docs/psyco/guangdong/shenzhen-kangning/index.md

补充康宁医院杨惠妮医生观察期信息

---

content/zh-cn/docs/srs/education.md

更新 学籍学历变更指引

---

content/zh-cn/docs/hrt/singapore/mount.md

feat(hrt): 添加新加坡伊丽莎白医院页面

---

content/zh-cn/docs/useful-info/document-updates/unitedstates.md

添加新的`海外证件信息修改`页面，更新了美国联邦变更流程及部分州的变更流程。

docs: Add document update guide in US.

---

content/zh-cn/docs/ffs/ffs-overview.md
content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md

1. **Facial Feminization Surgery (FFS)**:
- 添加 NM 的 3 位 FFS 医生（保险信息及联系方式）
2. **Voice Therapy**:
- 添加 UCI Health 的 1 位医生（保险疗程及 CPT code）
- 添加 NM 的 3 位医生（预约电话及流程）

docs: Update Resource Lists for Voice Therapy and FFS in US

---

.github/workflows/deploy.yaml
.github/workflows/preview-pr-build.yaml

已测试：https://github.com/Leetfs/blog/actions/runs/11984392123/job/33415114376

ci: 改用 wrangler-action@v3

---

content/zh-cn/docs/useful-info/document-updates/germany.md

- 修改文本地址为法律文本，保留 FAQ 地址作为参考
- 根据法律文本稍细化表达
- 更新致谢，增加 tfenise
相关讨论见 #1222 最后部分
感谢 @tfenise

德国 | 更新内容以符合法律文本

---

content/zh-cn/docs/hrt/australia/Sydney/index.md

docs: update Sydney

---

content/zh-cn/docs/hrt/jnuh1/index.md

添加医院别名（广州华侨医院）

---

package-lock.json
package.json

幸福倒计时，请坐和放宽
剑阁峥嵘而崔嵬，一夫当关，万夫莫开
本次更新带来了安全方面的改进
（提升 Suggestion Box 对用户的反馈，防止用户误以为没成功提交而刷屏）

chore(deps): :arrow_up: upgrade suggestion box

---

.github/workflows/preview-pr-build.yaml

再也不用手动删路径了~
**Full Changelog**: https://github.com/project-trans/pr-preview-action/compare/v1.0.0...v1.0.1

ci: Update pr-preview-action version

---

content/zh-hant/docs/medicine/estrogen/estradiol-valerate/index.md

https://mtf.wiki/zh-hant/docs/medicine/estrogen/estradiol-valerate/ 中Progynova的兩個劑量已經在香港註銷
Closes #1419

修改Progynova药物剂型过时信息

---

.github/workflows/preview-pr-build.yaml

相比现有基于 Hugo 实现的版本，新版带来了以下好处：
- 更好的性能，更流畅的阅读体验
- 保留了现有版本的几乎所有功能
- 新版激素换算器和胸围计算工具
- 增加对 [GitHub Flavored Markdown](https://github.github.com/gfm/) 等语法的支持，同时维持对目前 Hugo 语法的兼容性
- 带来更加现代的页面和现代的开发体验
作为第一步，考虑先将 MtF-wiki 主仓库的 PR preview 换成新版，以在正式上线前排查任何可能存在的问题。

PR 预览使用新版 MtF-wiki 前端框架

---

.github/workflows/deploy.yaml
.github/workflows/preview-pr-build.yaml
README-EN.md
README-ES.md
README-JA.md
README-T.md
README.md
content/en/about/_index.md
content/es/about/_index.md
content/ja/about/_index.md
content/zh-cn/about/_index.md
content/zh-hant/about/_index.md

使用新版 MtF-wiki 前端框架

---

content/zh-cn/docs/hrt/canada/uoft/index.md

补充了关于保险，处方药，以及看诊方面的内容，更新了一些过时的信息，更改了一些措辞以避免产生歧义

Update re University of Toronto

---

content/zh-cn/docs/hrt/canada/UWaterloo/index.md

- 新增HRT处方医生
- 更新验血时间
- 更新HRT时间规划（个案）
本更新基于留言箱反馈

更新 加拿大滑铁卢大学 HRT
